/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google() // optional, but protobuf ecosystem uses this
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "findItNow"

// Shared libraries
include("libs:common")
include("libs:config")
include("libs:database")
include("libs:redis")
include("libs:jwt")
include("libs:mail")
include("libs:quartz-scheduler")
include("libs:interservice-caller")

// Services
include("services:auth")

include("services:user-service")

include("libs:dispatcher")
include("libs:proto")
include("services:shop-service")
include("services:file-gateway")
include("services:order-service")
include("services:delivery-service")
include("services:review-system")